#!/usr/bin/env python3

import sys, os, requests, logging

logging.getLogger("requests").setLevel(logging.WARNING)

CONFIG_FILE = os.path.join(os.path.expanduser('~'), '.pasty.conf')
EXAMPLE_CONFIG = 'https://your.pasty.server.example.com'

def wrongConfigComplain(additional=None):
    print((
        'Configure pasty in ' + CONFIG_FILE + ' as follows:\n' +
        EXAMPLE_CONFIG
    ))

    if additional != None:
        print(additional)

    sys.exit()

def configIntegrity():
    try:
        config = open(os.path.expanduser(CONFIG_FILE))
        server = config.read()
        config.close()
    except:
        wrongConfigComplain()

    server = server.strip()
    if not 'http' in server or 'https' in server:
        wrongConfigComplain('\n\nyour are missing the protocol (http or https)')

    return server

if len(sys.argv) < 3 or len(sys.argv) > 4:
    print((
        'Pasty - command line tool\n\n'
        'DESCRIPTION\n'
        'This tool can be used to post posts to the Pasty web frontent\n'
        'to use this tool create a file ' + CONFIG_FILE + ' and enter the URL\n'
        'of the Pasty server\n\n'
        'USAGE\n'
        'pasty <format> <title> <file>\n\n'
        'where <title> is the title of the post, <file> is the file\n'
        'whose content gets posted and format is the format of the file\n'
        'which can either be md, code or text\n'
        'if <format> is not specified then md will be choosen'
    ))

    sys.exit()

if not os.path.isfile(CONFIG_FILE):
    wrongConfigComplain()

server = configIntegrity()


if len(sys.argv) == 4:
    display_mode = sys.argv[1]
    title = sys.argv[2]
    input_file = sys.argv[3]
else:
    display_mode = 'md'
    title = sys.argv[1]
    input_file = sys.argv[2]

display_mode_mapping = {
    'md' : 0,
    'code' : 1,
    'text' : 2
}

if display_mode_mapping.get(display_mode) == None:
    display_mode = 'md'

try:
    file = open(os.path.expanduser(input_file), 'r')
    content = file.read()
except:
    print('Failed to read file: ' + input_file)
    sys.exit()

try:
    rc = requests.post(server + '/save', data={
        'display_mode' : display_mode_mapping.get(display_mode),
        'title' : title,
        'content' : content
    })
    if rc.status_code != 200:
        print('Failed to contact server: ' + server + ' with error code: ' + rc.status_code)
    else:
        print((
        'Successfully posted ' + title + ' to Pasty\n'
        'Share this URL:\n\n'+ server + '/get/' + rc.text
        ))
except:
    print('Failed to contact server: ' + server)
